major speedup: compare between local and synced is now done with diff of the lists

diff --git a/sync_full b/sync_full
--- a/sync_full
+++ b/sync_full
@@ -4,6 +4,21 @@ set -euo pipefail
 
 PATH="$(dirname "$(readlink -e "$0")"):$PATH"
 
+
+function fetch_list_of_synced() {
+    local -r s3_url=$1
+    s3cmd -r ls "$s3_url" |\
+        sed -r 's|[0-9-]+[[:space:]]+[0-9:]+[[:space:]]+[0-9]+[[:space:]]+'"$s3_url"'(.+)|\1|' |\
+        sort
+}
+
+function list_all_local_files() {
+    local -r source_dir=$1
+    local -r include_tests=$2
+    find "$source_dir" -type f $include_tests -printf '%P\n' | sort
+}
+
+
 while getopts "b:d" opt; do
     case $opt in
         b )
@@ -15,33 +30,41 @@ while getopts "b:d" opt; do
 done
 shift $(expr $OPTIND - 1 )
 
-declare -r SOURCE_DIR=$1
-declare -r INCLUDE_PATTERN=$2
-declare -r S3_TARGET_URL=$3
 
-# TODO TBD checking each file individually if it has been synced already takes time... therefore, why not take both lists
-# (i.e. synced and all local files) and run them through diff to get the list of unsynced files?
-# diff call to get the unsynced files: diff --new-line-format="%L" synced.txt all.txt (--new-line-format param results in list with no leading "> ")
+source_dir=${1-}
+if [[ -z $(readlink -e "$source_dir") ]]; then
+    echo "[ERROR] Source directory missing $source_dir"
+    exit 1
+fi
 
-synced_list=$(s3cmd -r ls "$S3_TARGET_URL" |\
-    sed -r 's|[0-9-]+[[:space:]]+[0-9:]+[[:space:]]+[0-9]+[[:space:]]+'"$S3_TARGET_URL"'/(.+)|\1|')
+include_tests=${2-}
+if [[ -z $include_tests ]]; then
+    echo "[ERROR] Include tests for finding candidates missing" >&2
+    exit 1
+fi
 
-files=$(\
-    find "$SOURCE_DIR" -type f $INCLUDE_PATTERN -printf '%P\n' |\
-    while read candidate; do
-        grep -q "$candidate" <<<"$synced_list" || echo "$candidate"
-    done | sort
-)
+s3_target_url=${3-}
+if [[ -z $s3_target_url ]]; then
+    echo "[ERROR] S3 target url missing" >&2
+    exit 1
+fi
 
-if [[ -v BATCH_SIZE ]] && [[ -n $files ]]; then
-    echo "[INFO] Selecting batch of $BATCH_SIZE, full candidates count is $(wc -l <<<"$files")"
-    files=$(head -n "$BATCH_SIZE" <<<"$files")
+
+# --new-line-format="%L" will only output the line content, no ">" suffixes
+# the diff call needs the extra "|| true" because it will return 1 if there are differences
+candidates=$(diff --new-line-format='%L' --unchanged-line-format='  %L' --old-line-format= \
+    <(fetch_list_of_synced "$s3_target_url") \
+    <(list_all_local_files "$source_dir" "$include_tests") || true)
+
+if [[ -v BATCH_SIZE ]] && [[ -n $candidates ]]; then
+    echo "[INFO] Selecting batch of $BATCH_SIZE, full candidates count is $(wc -l <<<"$candidates")"
+    candidates=$(head -n "$BATCH_SIZE" <<<"$candidates")
 fi
 
 if [[ -v DRY_RUN ]]; then
-    echo "[INFO] Found $(wc -l <<<"$files") files to sync" >&2
-    echo "$files"
+    echo "[INFO] Found $(wc -l <<<"$candidates") files to sync" >&2
+    echo "$candidates"
     exit
 fi
 
-sync_files "$SOURCE_DIR" "$S3_TARGET_URL" <<<"$files"
+sync_files "$source_dir" "$s3_target_url" <<<"$candidates"
